
package face;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;


public class interFACE extends javax.swing.JFrame {
    Face f;
    Graphics pen;
 
    public interFACE() {
        initComponents();
        f = new Face(facePane1.getGraphics(), 100,100);
        boolean issad = (false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        facePane1 = new javax.swing.JPanel();
        movebtn = new javax.swing.JButton();
        sizebtn = new javax.swing.JButton();
        clrbtn = new javax.swing.JButton();
        moodbtn = new javax.swing.JButton();
        initbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        facePane1.setBackground(new java.awt.Color(255, 255, 255));
        facePane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout facePane1Layout = new javax.swing.GroupLayout(facePane1);
        facePane1.setLayout(facePane1Layout);
        facePane1Layout.setHorizontalGroup(
            facePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        facePane1Layout.setVerticalGroup(
            facePane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        movebtn.setText("Move Face");
        movebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movebtnActionPerformed(evt);
            }
        });

        sizebtn.setText("Resize Face");
        sizebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizebtnActionPerformed(evt);
            }
        });

        clrbtn.setText("Change Colour");
        clrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrbtnActionPerformed(evt);
            }
        });

        moodbtn.setText("Toggle Mood");
        moodbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moodbtnActionPerformed(evt);
            }
        });

        initbtn.setText("Set Initial Face");
        initbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                initbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(initbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(facePane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(movebtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(sizebtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clrbtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(moodbtn))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movebtn)
                    .addComponent(sizebtn)
                    .addComponent(clrbtn)
                    .addComponent(moodbtn))
                .addGap(18, 18, 18)
                .addComponent(facePane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(initbtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void movebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movebtnActionPerformed
        int newx = Integer.parseInt(JOptionPane.showInputDialog(this,"Enter New X"));
        int newy = Integer.parseInt(JOptionPane.showInputDialog(this,"Enter New Y"));
        f.erase();
        f.move(pen,newx,newy);
        f.draw();
    }//GEN-LAST:event_movebtnActionPerformed

    private void sizebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizebtnActionPerformed
        int newd = Integer.parseInt(JOptionPane.showInputDialog(this,"Enter new D"));
        f.erase();
        f.resize(pen,newd);
        
    }//GEN-LAST:event_sizebtnActionPerformed

    private void clrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrbtnActionPerformed
        Color newColor = JColorChooser.showDialog(this, "Pick new dice colour?", Color.red);
        f.setColor(newColor);
        f.draw();
    }//GEN-LAST:event_clrbtnActionPerformed

    private void moodbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moodbtnActionPerformed
        f.togglemood();
        f.erase();
        f.draw();
    }//GEN-LAST:event_moodbtnActionPerformed

    private void initbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initbtnActionPerformed
        moodbtn.setEnabled(true);
        clrbtn.setEnabled(true);
        sizebtn.setEnabled(true);
        movebtn.setEnabled(true);
        f.erase();
        f= new Face(facePane1.getGraphics(),50,50);
        f.draw();
    }//GEN-LAST:event_initbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interFACE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interFACE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clrbtn;
    private javax.swing.JPanel facePane1;
    private javax.swing.JButton initbtn;
    private javax.swing.JButton moodbtn;
    private javax.swing.JButton movebtn;
    private javax.swing.JButton sizebtn;
    // End of variables declaration//GEN-END:variables
}
